- platform: rest
  name: Clever Fælleden
  resource: https://clever.dk/umbraco/api/MapData/GetDetails?id=1337
  unit_of_measurement: stik
  json_attributes:
    - description
    - openingHours
  value_template: >
    {% set plugCount = namespace(value=0) %}
    {% for plug in value_json.plugs %}
      {% if "IEC_2" in plug.type %}
        {% if plug.isAvailable %}
          {% set plugCount.value = plugCount.value + 1 %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{plugCount.value}}

- platform: rest
  name: Clever Bloms
  resource: https://clever.dk/umbraco/api/MapData/GetDetails?id=1274
  unit_of_measurement: stik
  json_attributes:
    - description
    - openingHours
  value_template: >
    {% set plugCount = namespace(value=0) %}
    {% for plug in value_json.plugs %}
      {% if "IEC_2" in plug.type %}
        {% if plug.isAvailable %}
          {% set plugCount.value = plugCount.value + 1 %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{plugCount.value}}

- platform: rest
  name: Clever Kulturhuset
  resource: https://clever.dk/umbraco/api/MapData/GetDetails?id=1278
  unit_of_measurement: stik
  json_attributes:
    - description
    - openingHours
  value_template: >
    {% set plugCount = namespace(value=0) %}
    {% for plug in value_json.plugs %}
      {% if "IEC_2" in plug.type %}
        {% if plug.isAvailable %}
          {% set plugCount.value = plugCount.value + 1 %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{plugCount.value}}
