- platform: template
  sensors:
    livingroom_sun:
      friendly_name: Sol mængde gennem vindue i spisestue
      unit_of_measurement: "%"
      value_template: >
        {% set cover_opening = 100 %}
        {% if states('weather.hjem') != "cloudy" %}
          {% set deg2rad = pi/180 %}

          {% set sun_azi = state_attr('sun.sun', 'azimuth') | int %}
          {% set sun_ele = state_attr('sun.sun', 'elevation') | int %}

          {% set sun_x = cos(sun_azi*deg2rad)*cos(sun_ele*deg2rad) %}
          {% set sun_y = sin(sun_azi*deg2rad)*cos(sun_ele*deg2rad) %}
          {% set sun_z = sin(sun_ele*deg2rad) %}

          {% set win_azi = 43 %}
          {% set win_ele = 0 %}

          {% set cover_offset = 30 %}

          {% set win_x = cos(win_azi*deg2rad)*cos(win_ele*deg2rad) %}
          {% set win_y = sin(win_azi*deg2rad)*cos(win_ele*deg2rad) %}
          {% set win_z = sin(win_ele*deg2rad) %}

          {% set dot = sun_x*win_x + sun_y*win_y + sun_z*win_z %}
          {% set norm_win = sqrt(win_x**2 + win_y**2 + win_z**2) %}
          {% set norm_sun = sqrt(sun_x**2 + sun_y**2 + sun_z**2) %}
          {% set cos_sim = dot/(norm_win*norm_sun) %}

          {% set ang_sim = 1 - acos(cos_sim)/pi %}

          {% set cover_opening = (ang_sim * 100) + cover_offset %}

          {% if cover_opening > 100 %}
            {% set cover_opening = 100 %}
          {% endif %}
        {% endif %}

        {{ cover_opening | round(1) }}
