- platform: mqtt
  name: "Main-UPS Load"
  state_topic: "ups/main-ups/ups/status"
  value_template: "{{ value_json.load }}"

- platform: mqtt
  name: "GW-UPS Charge"
  state_topic: "ups/main-ups/ups/battery"
  value_template: "{{ value_json.charge }}"

- platform: mqtt
  name: "GW-UPS Runtime"
  state_topic: "ups/main-ups/ups/battery"
  value_template: "{{ value_json.runtime }}"

- platform: mqtt
  name: "GW-UPS Voltage"
  state_topic: "ups/main-ups/ups/battery"
  value_template: "{{ value_json.voltage }}"

- platform: mqtt
  name: "GW-UPS Online"
  state_topic: "ups/main-ups/state"
  value_template: "{{ value_json.online }}"
