- platform: ping
  host: 8.8.8.8
  name: WAN connection

- platform: ping
  host: 10.0.0.1
  name: VPN Ivan

- platform: ping
  host: 192.168.143.1
  name: VPN Horsensvej

- platform: ping
  host: 172.16.100.1
  name: VPN Hetzner

- platform: ping
  host: 192.168.1.199
  name: Fjernsyn Ping