- platform: broadlink
  mac: 78:0f:77:51:a3:e8
  switches:
    - name: Store Stearinlys
      command_on: JgB4AAABJZMUERQSFBIUERQSFBEUEhQSEzcUNhQ3FDYUNhQ3FDYUNxM3FBITEhQSFBEUEhQSExIUEhQ2FDcTNxQ2FDcUNhQ2FAAE5AABJUgTAAwtAAElSBMADC0AASVIEwAMJAABLkgUAAwsAAEmSBMACz0NGgsKHAANBQ==
      command_off: JgCsAAABJZMUERQSFBITEhQSFBEUEhQSEzcUNhQ3EykiJyM3EzcUNhQ3ExIUNhQSFBIUERQSFBITEhQ3ExIUNxM3FDYUNxM3FAAE4gABJUkTAAwpAAElSRMAAXxrAApEAAEmSBMADC0AASZGFY1oAAs4AAElSRMADC0AASUnNQAMLQABJkgTAAwuAAElSRMADC0AASZIEwALXmplAAElSBMADCsAASZIEwAKa2wADQUAAAAAAAAAAAAAAAA=

- platform: broadlink
  mac: 78:0f:77:51:a3:e8
  switches:
    - name: Fyrfadslys
      command_on: JgBoAAABLpQUExMTFBMTExMUExMTFBIUEjgTNxM3EjgTNxM3EjgSOBI4ExQSFBIVExMSFRIUEhUTExM3EjgTNxI4EzcTNxI4EgAFFQABLkoTAAxaAAEvShIADFsAAS5KEgAMWwABLkoUAA0F
      command_off: JgB4AAABLpQSFRMTEhUSFBIUExQSFBMUEzcTNxI4EzcTNxI4EjgSOBI4EhQSFBQ2ExQTExMUEhQTFBM2FDYTFBI4EjgSOBI4EwAFFQABLUsSAAxeAAEtSxIADF4AAS1LEwAMXQABLUsTAAxdAAEuShMADF0AAS1LEwANBQ==