esphome:
  name: ${node_name}
  build_path: ./build/${node_name}
  platform: ${platform}
  board: ${board}

api:
  reboot_timeout: 1h

ota:
  safe_mode: True

text_sensor:
  - <<: !include text_sensor/uptime.yaml

sensor:
  - <<: !include sensor/uptime.yaml
  - <<: !include sensor/wifi_signal.yaml
binary_sensor:
  - <<: !include binary_sensor/connection_status.yaml

#switch:
#  - <<: !include switch/safemode.yaml

button:
  - <<: !include button/restart.yaml