automation:
  - alias: Auto - CBB - Parsehub - Update State
    id: cbbUpdateState
    description: Triggers update thru Parsehub
    trigger:
      - platform: time_pattern
        hours: /1
    action:
      - service: shell_command.parsehub_run
        data_template:
          token: !secret token_cbb
    mode: single

  - alias: Auto - CBB - Parsehub - Fetch JSON after run
    id: cbbFetchState
    description: Fetch JSON data after finished run
    trigger:
      - platform: webhook
        webhook_id: !secret webhook_cbb
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: '{{ trigger.data.data_ready == "1" }}'
            sequence:
              - service: shell_command.parsehub_fetch
                data_template:
                  token: !secret token_cbb
                  filename: 'cbb.json'
    mode: restart

sensor:
  - platform: file
    file_path: /config/www/rest/cbb.json
    name: 'CBB Talk'
    value_template: >
      {% if value_json.Talk %}
        {{ value_json.Talk }}
      {% else %}
        {{ states("sensor.cbb_talk") }}
      {% endif %}

  - platform: file
    file_path: /config/www/rest/cbb.json
    name: 'CBB Data DK'
    value_template: >
      {% if value_json.DataDK %}
        {{ value_json.DataDK }}
      {% else %}
        {{ states("sensor.cbb_data_dk") }}
      {% endif %}

  - platform: file
    file_path: /config/www/rest/cbb.json
    name: 'CBB Data EU'
    value_template: >
      {% if value_json.DataEU %}
        {{ value_json.DataEU }}
      {% else %}
        {{ states("sensor.cbb_data_eu") }}
      {% endif %}

  - platform: file
    file_path: /config/www/rest/cbb.json
    name: 'CBB Messages'
    value_template: >
      {% if value_json.Messages %}
        {{ value_json.Messages }}
      {% else %}
        {{ states("sensor.cbb_messages") }}
      {% endif %}

  - platform: file
    file_path: /config/www/rest/cbb.json
    name: 'CBB Extra'
    value_template: >
      {% if value_json.Extra %}
        {{ value_json.Extra }}
      {% else %}
        {{ states("sensor.cbb_extra") }}
      {% endif %}