##########################
# AMS Reader MQTT topics #
##########################

sensor:
  - platform: mqtt
    name: Kamstrup RSSI
    state_topic: "kamstrup/rssi"
    device_class: signal_strength
    unit_of_measurement: dBm
    unique_id: amsrssi
  - platform: mqtt
    name: Kamstrup Import
    state_topic: "kamstrup/meter/import/active"
    state_class: measurement
    device_class: power
    unit_of_measurement: W
    unique_id: amsimport
  - platform: mqtt
    name: Kamstrup Meter Reading
    state_topic: "kamstrup/meter/import/active/accumulated"
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    unique_id: amsimportaccumulated
  - platform: mqtt
    name: Kamstrup L1 PowerFactor
    state_topic: "kamstrup/meter/l1/powerfactor"
    device_class: power_factor
    unit_of_measurement: "%"
    unique_id: amsl1powerfactor
  - platform: mqtt
    name: Kamstrup L1 Current
    state_topic: "kamstrup/meter/l1/current"
    device_class: current
    unit_of_measurement: A
    unique_id: amsl1current
  - platform: mqtt
    name: Kamstrup L1 Voltage
    state_topic: "kamstrup/meter/l1/voltage"
    device_class: voltage
    unit_of_measurement: V
    unique_id: amsl1voltage
  - platform: mqtt
    name: Kamstrup L2 PowerFactor
    state_topic: "kamstrup/meter/l2/powerfactor"
    device_class: power_factor
    unit_of_measurement: "%"
    unique_id: amsl2powerfactor
  - platform: mqtt
    name: Kamstrup L2 Current
    state_topic: "kamstrup/meter/l2/current"
    device_class: current
    unit_of_measurement: A
    unique_id: amsl2current
  - platform: mqtt
    name: Kamstrup L2 Voltage
    state_topic: "kamstrup/meter/l2/voltage"
    device_class: voltage
    unit_of_measurement: V
    unique_id: amsl2voltage
  - platform: mqtt
    name: Kamstrup L3 PowerFactor
    state_topic: "kamstrup/meter/l3/powerfactor"
    device_class: power_factor
    unit_of_measurement: "%"
    unique_id: amsl3powerfactor
  - platform: mqtt
    name: Kamstrup L3 Current
    state_topic: "kamstrup/meter/l3/current"
    device_class: current
    unit_of_measurement: A
    unique_id: amsl3current
  - platform: mqtt
    name: Kamstrup L3 Voltage
    state_topic: "kamstrup/meter/l3/voltage"
    device_class: voltage
    unit_of_measurement: V
    unique_id: amsl3voltage

# Subtract cost-tracked entities from the total meter reading
template:
  - sensor:
      - name: "Kamstrup Meter Reading Without Sensors"
        device_class: energy
        state_class: total_increasing
        unit_of_measurement: kWh
        state: >
          {% set old_state = states.sensor.kamstrup_meter_reading_without_sensors.state | float(0) %}
          {% set new_state = (states.sensor.kamstrup_meter_reading.state | float(0)) - (expand('group.energy_sensors') | rejectattr('state','in',['unavailable','unknown','none']) | map(attribute='state') | map('float') | sum() | round(2)) %}
          {% set diff = (new_state - old_state) %}

          {% if (diff > 2 or diff < -1) and old_state > 0 %}
            {{ old_state }}
          {% else %}
            {{ new_state }}
          {% endif %}
      - name: "Kamstrup Meter Reading Without Sensors - Diff"
        unit_of_measurement: kWh
        state: >
          {% set old_state = states.sensor.kamstrup_meter_reading_without_sensors.state | float(0) %}
          {% set new_state = (states.sensor.kamstrup_meter_reading.state | float(0)) - (expand('group.energy_sensors') | rejectattr('state','in',['unavailable','unknown','none']) | map(attribute='state') | map('float') | sum() | round(2)) %}
          {{ (new_state - old_state) }}
