start:
  description: Start mowing
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum

pause:
  description: Pause mowing
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum

home:
  description: Send device to dock
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum

lock:
  description: Toggle device lock
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum

restart:
  description: Restart device
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum

edgecut:
  description: Start edgecut (if supported)
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum

partymode:
  description: Toggle PartyMode (if supported)
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum

setzone:
  description: Set which zone to be mowed next
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum
  fields:
    zone:
      description: Sets the zone number, ranging from 0 to 3, to be mowed next
      example: 1
      required: true
      default: "0"
      selector:
        select:
          options:
            - "0"
            - "1"
            - "2"
            - "3"

config:
  description: Set device config parameters
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum
  fields:
    raindelay:
      description: Set rain delay. Time in minutes ranging from 0 to 300. 0 = Disabled
      example: 30
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: "minutes"
          mode: slider
    timeextension:
      description: Set time extension. Extension in % ranging from -100 to 100
      example: -23
      selector:
        number:
          min: -100
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    multizone_distances:
      description: 'Set multizone distance array in meters. 0 = Disabled. Format: [15, 80, 120, 155]'
      example: '[15, 80, 120, 155]'
      selector:
        text:
    multizone_probabilities:
      description: 'Set multizone probabilities array. Probabilities in parts-of-ten. 1 = 10%, 2 = 20%, ... Format: [5, 1, 2, 2]'
      example: '[5, 1, 2, 2]'
      selector:
        text:

ots:
  description: Start One-Time-Schedule (if supported)
  target:
    entity:
      integration: landroid_cloud
      domain: vacuum
  fields:
    boundary:
      description: Do boundary cut
      example: true
      required: true
      default: false
      selector:
        boolean:
    runtime:
      description: Runtime in minutes
      example: 60
      required: true
      default: 30
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: "minutes"
          mode: slider