substitutions:
  node_name: wavin
  device_verbose_name: "Wavin"
  device: wavin
  name: Wavin
  board: nodemcu
  platform: ESP8266
  log_level: DEBUG

# CHANNEL friendly names (If using spaces remember to add ")
  channel_01_friendly_name: Toilet
  channel_02_friendly_name: Bedroom
  channel_03_friendly_name: Hall
  channel_04_friendly_name: "Channel 04"
  channel_05_friendly_name: "Channel 05"
  channel_06_friendly_name: "Channel 06"
  channel_07_friendly_name: "Channel 07"
  channel_08_friendly_name: "Channel 08"
  channel_09_friendly_name: "Channel 09"
  channel_10_friendly_name: "Channel 10"
  channel_11_friendly_name: "Channel 11"
  channel_12_friendly_name: "Channel 12"
  channel_13_friendly_name: "Channel 13"
  channel_14_friendly_name: "Channel 14"
  channel_15_friendly_name: "Channel 15"
  channel_16_friendly_name: "Channel 16"
  

# CHANNEL ID´S (ONLY LOWER CASE LETTERS, NO SPACES) used for entity ids
  channel_01_id: toilet
  channel_02_id: bedroom
  channel_03_id: hall
  channel_04_id: channel_04
  channel_05_id: channel_05
  channel_06_id: channel_06
  channel_07_id: channel_07
  channel_08_id: channel_08
  channel_09_id: channel_09
  channel_10_id: channel_10
  channel_11_id: channel_11
  channel_12_id: channel_12
  channel_13_id: channel_13
  channel_14_id: channel_14
  channel_15_id: channel_15
  channel_16_id: channel_16
  
packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  web: !include common/web.yaml
  remote_package:
    url: https://github.com/heinekmadsen/esphome_components
    ref: main
    files: 
      - components/wavinahc9000v2/configs/channel_01.yaml 
      - components/wavinahc9000v2/configs/channel_02.yaml 
      - components/wavinahc9000v2/configs/channel_03.yaml 
    refresh: 0s

# Disable logger
logger:
  baud_rate: 0

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 38400
  id: uart_${device}
  stop_bits: 1
  parity: NONE
    
modbus:
  - id: ${device}_modbus
    uart_id: uart_${device}

modbus_controller:
  id: ${device}_modbus_controller
  address: 1
  modbus_id: wavin_modbus
  update_interval: 5s