esphome:
  name: wavin
  platform: ESP8266
  board: nodemcu

external_components:
  - source: github://heinekmadsen/esphome_components

wifi:
  ssid: !secret esp_ssid
  password: !secret esp_wpa
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: "hGK7orjlHnLm"

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 38400
  id: uart_modbus
  stop_bits: 1
    
modbus:
  uart_id: uart_modbus

wavinAhc9000:
  update_interval: 60s
  rw_pin: GPIO5

climate:
  - platform: wavinAhc9000
    channel: 1
    name: "Toilet"
    visual:
      temperature_step: 0.5 °C
    battery_level:
      name: "Toilet Battery"
    current_temp:
      name: "Toilet Temperature"
  - platform: wavinAhc9000
    channel: 2
    name: "Bedroom"
    visual:
      temperature_step: 0.5 °C
    battery_level:
      name: "Bedroom Battery"
    current_temp:
      name: "Bedroom Temperature"
  - platform: wavinAhc9000
    channel: 3
    name: "Hall"
    visual:
      temperature_step: 0.5 °C
    battery_level:
      name: "Hall Battery"
    current_temp:
      name: "Hall Temperature"
